// Autor: JeanCarloEM.com
// Site do Autor: https://jeancarloem.com
// Repositorio: https://github.com/jcempro/agents.md
// Licenca: Mozilla Public License 2.0
// Site da Licenca: https://www.mozilla.org/MPL/2.0/
// Resumo da Licenca: uso, copia, modificacao e distribuicao permitidos conforme os termos da MPL-2.0.
// Disclaimer: fornecido AS IS, sem garantias de qualquer tipo.
// Gerado de: src/.ia.rules/scenarios/release/scripts/release-publish.ts; TypeScript 7.0.2 + esbuild 0.28.1; Node 24+.

const N=require("child_process"),h=require("fs"),f=require("path"),{loadConfiguration:T}=require("../../../core/runtime/scripts/configuration"),{normalizeReleaseVersion:I}=require("./release-workflow"),u=f.resolve(__dirname,"..","..","..",".."),m=T(u),d=f.join(u,"package.json");class c extends Error{}function g(r=process.argv.slice(2)){const e=R(r);if(e.help)return process.stdout.write(p()),0;const t=I(e.version),o=_(t,e);if(e.dryRun)return A({code:"RELEASE_PUBLISH_DRY_RUN",...o,configuration:w(e),version:t,watch:!e.noWatch}),0;$(o),y(t,e),b(t,e);const n=L(t,e),i=e.noWatch||!o.gh?null:P(t,n.commit,e);return A({code:i?"RELEASE_PUBLISH_OK":"RELEASE_TRIGGER_ENVIADO",configuration:w(e),githubCli:o.gh,triggerCommit:n.commit,version:t,...i||{}}),0}function R(r){const e={branch:process.env.AGENTS_RELEASE_BRANCH||m.lifecycle.developmentBranch,dryRun:!1,help:!1,noWatch:!1,primary:process.env.AGENTS_RELEASE_PRIMARY||"",remote:process.env.AGENTS_RELEASE_REMOTE||m.lifecycle.remote,version:"",workflow:process.env.AGENTS_RELEASE_WORKFLOW||m.lifecycle.workflow};for(let t=0;t<r.length;t+=1){const o=r[t];if(o==="--dry-run")e.dryRun=!0;else if(o==="--help")e.help=!0;else if(o==="--no-watch")e.noWatch=!0;else if(["--branch","--primary","--remote","--workflow"].includes(o)){const n=o.slice(2);if(e[n]=r[++t]||"",!e[n])throw new c(`PARAMETRO_NORMATIVO_AUSENTE:${n}`)}else{if(o.startsWith("-"))throw new c(`PARAMETRO_INVALIDO:${o}`);if(!e.version)e.version=o;else throw new c(`PARAMETRO_INVALIDO:${o}`)}}if(!e.help&&!e.version)throw new c("PARAMETRO_NORMATIVO_AUSENTE:version");for(const t of["branch","primary","remote"])if(e[t]&&!/^[A-Za-z0-9._/-]+$/u.test(e[t]))throw new c(`PARAMETRO_INVALIDO:${t}`);if(!/^[A-Za-z0-9._-]+\.ya?ml$/u.test(e.workflow))throw new c("PARAMETRO_INVALIDO:workflow");return e}function p(){return`Uso: release:publish <versao> [--dry-run] [--no-watch] [--branch <nome>] [--primary <nome>] [--remote <nome>] [--workflow <arquivo.yml>]
`}function w(r){return{branch:r.branch,primary:r.primary,remote:r.remote,workflow:r.workflow}}function _(r,e={branch:"dev",workflow:"release.yml"}){const t=s("git",["branch","--show-current"]).stdout.trim(),o=s("git",["status","--porcelain"],{optional:!0}).stdout.trim().split(/\r?\n/u).filter(Boolean),n=`v${r}`,i=s("git",["rev-parse","--verify",`refs/tags/${n}`],{optional:!0}).status===0,a=f.join(u,".github","workflows",e.workflow),l=s("gh",["--version"],{optional:!0}).status===0;return{branch:t,dirty:o,expectedBranch:e.branch,gh:l,localTag:i,tag:n,workflow:h.existsSync(a)}}function $(r){if(r.branch!==r.expectedBranch)throw new Error(`BRANCH_RELEASE_INVALIDA:${r.branch||"(vazia)"}`);if(r.dirty.length)throw new Error(`WORKTREE_NAO_LIMPO:${r.dirty.join(",")}`);if(r.localTag)throw new Error(`VERSAO_JA_PUBLICADA:${r.tag}`);if(!r.workflow)throw new Error("WORKFLOW_RELEASE_AUSENTE:.github/workflows/release.yml")}function y(r,e){const t=JSON.parse(h.readFileSync(d,"utf8"));t.version=r,h.writeFileSync(d,`${JSON.stringify(t,null,2)}
`,"utf8"),s("git",["add","--","package.json"]),E(["package.json"]),s("git",["commit","-m",`chore: prepara release v${r}`]),s("git",["push",e.remote,e.branch],{timeout:12e4})}function b(r,e){if(s(process.execPath,[f.join(u,".ia.rules","core","runtime","scripts","repo-tools.js"),"agent:release",r],{timeout:9e5}),s(process.execPath,[f.join(u,".ia.rules","core","runtime","scripts","repo-tools.js"),"agent:verify"],{timeout:9e5}),s("git",["add","--","dist","index.json"]),!s("git",["diff","--cached","--name-status","--","dist","index.json"]).stdout.trim()){if(!s("git",["log","-1","--format=%H","--","dist","index.json"]).stdout.trim())throw new Error(`COMMIT_ARTEFATO_RELEASE_AUSENTE:v${r}`);s("git",["push",e.remote,e.branch],{timeout:12e4});return}E(["dist/","index.json"],{prefixes:!0}),s("git",["commit","-m",`chore: gera artefato v${r}`]),s("git",["push",e.remote,e.branch],{timeout:12e4})}function L(r,e){if(O(r),s("git",["add","--","release"]),!s("git",["diff","--cached","--name-status","--","release"]).stdout.trim()){const n=s("git",["log","-1","--format=%H","--","release"]).stdout.trim();if(!n)throw new Error(`COMMIT_GATILHO_RELEASE_AUSENTE:v${r}`);return s("git",["push",e.remote,e.branch],{timeout:12e4}),{commit:n,reused:!0}}E(["release"],{statuses:["A","M"]}),s("git",["commit","-m",`chore: aciona release v${r}`]);const o=s("git",["rev-parse","HEAD"]).stdout.trim();return s("git",["push",e.remote,e.branch],{timeout:12e4}),{commit:o}}function O(r){const e=s(process.execPath,[f.join(u,".ia.rules","core","runtime","scripts","repo-tools.js"),"agent:release:trigger",r],{optional:!0});if(!e.error&&e.status===0||S(e))return e;throw new Error(`${process.execPath} .ia.rules/core/runtime/scripts/repo-tools.js agent:release:trigger ${r} falhou: ${e.error?e.error.message:e.stderr||e.stdout}`)}function S(r){const e=`${r.stdout||""}
${r.stderr||""}`;return/\b(?:RELEASE_TRIGGER_EXISTENTE|GATILHO_RELEASE_EXISTENTE)\b/u.test(e)}function P(r,e,t){const o=v(e,t);s("gh",["run","watch",o,"--exit-status"],{timeout:9e5});const n=k(t);s("git",["fetch",t.remote,t.branch,n],{timeout:12e4}),s("git",["pull","--ff-only",t.remote,t.branch],{timeout:12e4});const i=s("git",["rev-parse",`${t.remote}/${t.branch}`]).stdout.trim(),a=s("git",["rev-parse",`${t.remote}/${n}`]).stdout.trim();if(i!==a)throw new Error(`CONVERGENCIA_REMOTA_PENDENTE:dev=${i};${n}=${a}`);const l=JSON.parse(s("gh",["release","view",`v${r}`,"--json","url,tagName,isDraft,isPrerelease"],{timeout:12e4}).stdout);if(l.tagName!==`v${r}`||l.isDraft||l.isPrerelease)throw new Error(`RELEASE_REMOTO_INVALIDO:v${r}`);return{primary:n,releaseUrl:l.url,workflowRun:Number(o)}}function v(r,e){for(const t of[0,1e3,3e3]){t&&j(t);const o=s("gh",["run","list","--workflow",e.workflow,"--branch",e.branch,"--event","push","--limit","20","--json","databaseId,headSha"],{optional:!0,timeout:12e4});if(o.status!==0)continue;const n=JSON.parse(o.stdout).find(i=>i.headSha===r);if(n)return String(n.databaseId)}throw new Error(`WORKFLOW_RELEASE_NAO_ENCONTRADO:${r}`)}function k(r){const e=r.primary?[r.primary]:["main","master"];for(const t of e)if(s("git",["ls-remote","--exit-code","--heads",r.remote,t],{optional:!0,timeout:12e4}).status===0)return t;throw new Error("BRANCH_PRIMARIA_AUSENTE")}function E(r,e={}){const t=s("git",["diff","--cached","--name-status"]).stdout.trim().split(/\r?\n/u).filter(Boolean).map(o=>{const[n,i]=o.split(/\t/u);return{filePath:i,status:n}});if(!t.length||t.some(o=>{const n=e.prefixes?r.some(a=>o.filePath===a||o.filePath.startsWith(a)):r.includes(o.filePath),i=!e.statuses||e.statuses.includes(o.status);return!n||!i}))throw new Error(`STAGING_RELEASE_INVALIDO:${t.map(o=>`${o.status}:${o.filePath}`).join(",")}`)}function s(r,e,t={}){const o=N.spawnSync(r,e,{cwd:u,encoding:"utf8",shell:!1,timeout:t.timeout||3e4});if(!t.optional&&(o.error||o.status!==0))throw new Error(`${r} ${e.join(" ")} falhou: ${o.error?o.error.message:o.stderr||o.stdout}`);return o}function j(r){Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,r)}function A(r){process.stdout.write(`${JSON.stringify(r)}
`)}if(require.main===module)try{process.exitCode=g()}catch(r){process.stderr.write(`${r.message}
`),process.exitCode=r instanceof c?2:1}module.exports={help:p,inspectPreflight:_,isExistingTriggerResult:S,main:g,parseArgs:R,runReleaseTrigger:O};
