const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'../../../..'),file=path.join(root,'_drafts/carta-aberta-hierarquia-romanda-na-igreja');
const {applyEditorialEdits}=require(path.join(root,'.ia.rules/core/runtime/scripts/editorial-authoring.js'));
const original=fs.readFileSync(file,'utf8'),edits=[];
function para(prefix,replacement){const start=original.indexOf(prefix);if(start<0||original.indexOf(prefix,start+1)>=0)throw Error('Prefixo não unívoco: '+prefix);let end=original.indexOf('\n\n',start);if(end<0)throw Error('Fim ausente');edits.push({start,end,expected:original.slice(start,end),replacement,kind:'editorial',reason:'FT-112 M09a: preservar intensidade e corrigir atribuição/alcance'});}
para('Os apóstolos se alegraram',`Os apóstolos se alegraram por sofrer pelo nome de JESUS.[^at541] Também há motivo de alegria quando a rejeição confirma, na experiência, o que a Palavra advertiu. É assim que alguns de nós temos nos sentido: uma experiência **agridoce**, felizes por sermos achados dignos de sofrer pelo nome de CRISTO e tristes pelo estado lastimável da igreja. **A prova decisiva é a fidelidade à VERDADE.** O alvoroço pode acompanhar a rejeição da verdade; sozinho, porém, não é evidência inequívoca de que o mensageiro esteja certo. João escreveu que “o mundo inteiro jaz no Maligno”.[^1jo519] A verdade confronta esse domínio, embora nem toda reação seja ruidosa e nem todo erro produza tranquilidade. Essa distinção **NÃO autoriza silenciar** uma advertência já demonstrada pela Palavra.`);
para('A denúncia é que, **não no todo**',`A denúncia é que, **não no todo**, mas em **grande medida**, a igreja está atuando no _modus operandi_ — no modo de agir — de **hierarquia papal**. Os testemunhos já denunciavam esse mal nos dias de Ellen White. Esta carta existe justamente porque há a promessa: **não cairá**. Na imagem aqui empregada, meus poucos irmãos e eu somos os poucos **anticorpos remanescentes** de um **corpo moribundo**,[^me2380] lutando, **NÃO por nós mesmos**, contra uma maioria de células cancerígenas: uma metástase, o câncer espalhado pelo corpo. É a minha imagem para denunciar o **<u>domínio do pecado</u> na igreja**, não no mundo; não declara ninguém fora do alcance da conversão. Ellen White diz que a igreja poderá parecer prestes a cair; **“moribunda” é a metáfora desta carta**, não uma palavra que aquele trecho atribua a CRISTO. Por João, Laodiceia recebe um diagnóstico terrível, seguido do remédio e do chamado ao arrependimento. A boa notícia é que a operação de JESUS é **sobrenatural**![^ap3]`);
para('Note: **“Ao <u>APROXIMAR-SE</u>',`Note: **“Ao <u>APROXIMAR-SE</u> a tempestade”**. Não somente quando ela tiver chegado: **na aproximação**! Os sinais que observo, especialmente depois da pandemia, tornam difícil imaginar que este mundo prossiga indefinidamente assim. A seguir exponho uma **reflexão pessoal, sem alegar comprovação** de uma 3ª Guerra Mundial em curso. Tenho em vista também análises atribuídas a historiadores e militares ligados à OTAN; sem identificar individualmente essas fontes, não as uso como prova. A pergunta que faço é esta: se uma guerra direta entre as grandes potências nucleares poderia produzir destruição catastrófica, faz sentido esperar que o conflito mundial repita exatamente o modelo das guerras anteriores para reconhecê-lo? Essa possibilidade me inquieta; não a apresento como certeza histórica ou profética.`);
para('A pergunta surgiu durante SUA',`A pergunta surgiu durante SUA caminhada para Jerusalém. A resposta confronta pessoas que poderiam alegar proximidade com ELE e ainda ficar de fora.[^lc13contexto] A advertência alcança o **povo religioso**; **NÃO** pode ser empurrada indevidamente para o mundo, como se a igreja estivesse dispensada de ouvi-la. João escreveu: _“Veio para o que era seu, e os seus não o receberam.”_[^jo111] O golpe contra a falsa segurança religiosa é **certeiro e cirúrgico**. Membros, discípulos e líderes **DEVEM recebê-lo**. Lucas, porém, não identifica o interlocutor de modo que possamos afirmar que a frase foi dirigida exclusivamente a líderes ou a membros da igreja atual; tampouco fornece uma estatística deles.`);
para('Portanto, sinto muito dizer:',`Portanto, sinto muito dizer: se você **amortece a VERDADE** para impedir que ela sacuda a igreja, **<u>VOCÊ ESTÁ CONTRA DEUS</u>**. A mensagem para este tempo sacode e peneira o que precisa ser sacudido, causa alvoroço e confronta até os vínculos mais próximos. Nas palavras de JESUS: “Eu vim para pôr os filhos contra os pais, as filhas contra as mães e as noras contra as sogras.”[^mt1035] Não é o barulho da reação, o alvoroço ou a crise que mede a fidelidade; é **a mensagem que se anuncia ou se esconde**. Ellen White **NÃO se arrependeu da firmeza**: declarou que seu erro, se houve, foi **NÃO repreender MAIS FIRME** e decididamente o pecado, como já lemos.`);
para('Vivemos neste mundo miserável',`Vivemos neste mundo miserável, cheio de dor, morte e sofrimento, enquanto **pessoas covardes e acanhadas** evitam pregar a mensagem **verdadeira, tal como ela é**, em **posição OUSADA**. Nós todos respondemos pela missão que nos foi confiada. Cada ferida, cada tiroteio, cada estupro, cada câncer, cada lágrima e cada pessoa que chora tornam essa responsabilidade aterradora. Não somos os autores de todos esses males; somos culpados quando recebemos luz para advertir e escolhemos pisar em ovos. **Estamos sendo covardes!** O testemunho abaixo atribui consequências reais à infidelidade do povo: a obra poderia ter terminado, e JESUS já poderia ter retornado. Se, diante da possibilidade de silenciamento ou de um processo, já recuamos, o que faremos quando houver proibição de pregar sobre o sábado e imposição de trabalhar nele? Esses não são os únicos riscos existentes em todo lugar hoje; o contraste denuncia nossa falta de coragem diante das pressões que já enfrentamos. “Bem está, servo bom e fiel. Sobre o pouco foste fiel, sobre muito te colocarei”.[^mt2521]`);
para('> ⁷ Pois Deus',`> ⁷ Porque Deus não nos tem dado espírito de **covardia**, mas de **poder**, de **amor** e de **moderação**.
> — Bíblia, ARA. 2 Timóteo 1:7`);
para('> "Mas, quanto aos **covardes**',`> Quanto, porém, aos **covardes**, [...] a parte que lhes cabe será no lago que arde com fogo e enxofre, [...] a segunda morte.
> — Bíblia, ARA. Apocalipse 21:8`);
para('A maioria ainda hoje se negam',`A maioria ainda hoje se nega a ouvir — essa é a denúncia que faço — e não tem recebido a mensagem do **TERCEIRO anjo**. Em 1901, outra declaração vem fazer cair o queixo e levar às lágrimas quem ama a verdade e deseja sair o mais rápido possível deste mundo. Eu sou um desses. **Não vejo a hora de estar com CRISTO!** Paulo escreveu: _“Porquanto, para mim, o viver é Cristo, e o morrer é lucro.”_[^fp121] Lucro é **ganho**, algo desejável: estar com CRISTO era seu anseio, **incomparavelmente melhor**. Viver não era buscar diversão, prazer egoísta ou acumulação; era **missão**. Mas Paulo também queria permanecer para o progresso e a alegria da fé dos irmãos. Não se pode converter esse anseio em afirmação de que jamais experimentasse alegria na vida ou de que a morte fosse um objetivo a provocar. O ganho supremo era **CRISTO**, não a morte em si. A felicidade do reino futuro eclipsa os atrativos deste mundo; enquanto aqui permanecemos, a saudade do Céu **EXIGE fidelidade à missão**.`);
para('Ellen White também descreve a tristeza',`Ellen White também descreve a tristeza de voltar da visão de um mundo melhor e as saudades do que vira.[^pe20] O contraste entre o paraíso contemplado e a Terra era esmagador. Podemos reconhecer a profundidade dessa tristeza sem lhe atribuir retrospectivamente um diagnóstico de depressão. Quem tem CRISTO no coração não pode encontrar satisfação final nas coisas terrenas. É nesse anseio que a declaração de 1901 atinge em cheio: **insubordinação**. O ser humano sempre encontra uma desculpa para **acomodar-se** e evitar **transformar-se**. Aqui, sujeição importa em _“transformai-vos pela renovação da vossa mente”_,[^rm122] assim como em _“permanecei em mim, e eu permanecerei em vós”_.[^jo154] O querer e a capacidade de fazer vêm de DEUS, não de uma força humana independente.[^fp213] Graça NÃO é meramente o poder que perdoa, mas o poder que **salva <u>E</u> transforma**.`);
para('Ensinar um graça que apenas salva',`Ensinar uma graça que perdoa, mas deixa o pecador entregue ao domínio do pecado, é pregar uma **meia verdade que falsifica o evangelho**. Uma graça separada da transformação é uma graça manca; esvazia-se, assim, o propósito da cruz, que liberta da culpa e do poder do pecado. Digo-o de forma contundente: **“99,99% salvo” ainda é “100% perdido”**, se com isso alguém pretende conservar deliberadamente sua parte de rebelião. É uma imagem da entrega dividida, não uma porcentagem real da salvação nem a exigência de comprar o perdão com desempenho. Do mesmo modo, falar em “99,99% vivo e 100% morto” só funciona como figura dessa contradição espiritual, jamais como afirmação biológica. A graça deve ser recebida **inteiramente**, para perdoar e transformar. O “por pouco” de Agripa não deve tornar-se nosso abrigo: a resposta de Paulo aponta para ser cristão de fato, não para repousar numa quase adesão.[^agripa] Apocalipse 14:12 apresenta ambos:`);
para('Portanto, NÃO exite graça',`Portanto, **NÃO existe fé viva sem transformação**, nem transformação salvadora produzida por obras independentes da fé. Por isso a denúncia de insubordinação importa tanto: o problema não é falta de profissão de fé ou de conhecimento doutrinário, mas a recusa de praticar o que se professa. Não chamemos de fé salvadora aquilo que permanece sem frutos: **a fé sem obras é morta**.[^tg217] A revelação de 1901 diz:`);
const notes=`
[^1jo519]: Bíblia, ARA. [1 João 5:19](https://www.bibliaonline.com.br/ara/1jo/5). O domínio do Maligno no mundo não torna qualquer oposição sofrida prova automática de fidelidade.
[^mt1035]: Bíblia, NTLH. [Mateus 10:35](https://www.bible.com/pt/bible/211/MAT.10.35.NTLH). O contexto anuncia divisão provocada pela fidelidade a JESUS; não ordena fabricar conflitos.
[^mt2521]: Bíblia, ACF. [Mateus 25:21](https://www.bibliaonline.com.br/acf/mt/25/21-26), na parábola dos talentos.
[^agripa]: Bíblia, Atos 26:28–29. A resposta de Agripa, tradicionalmente vertida como “por pouco”, não oferece uma medida percentual da salvação; Paulo deseja a conversão efetiva dos ouvintes.
[^tg217]: Bíblia, Tiago 2:17–18,26; cf. Efésios 2:8–10. Obras como fruto e manifestação da fé, não preço do perdão.
`;
const result=applyEditorialEdits(original,edits);fs.writeFileSync(file,result.markedOutput+'\n'+notes);
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');fs.writeFileSync(path.join(__dirname,'aplicacao-M09a.json'),JSON.stringify({before:hash(original),after:hash(result.markedOutput+'\n'+notes),regions:result.regions},null,2));console.log(edits.length+' regiões aplicadas.');
