const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'../../../..'),file=path.join(root,'_drafts/carta-aberta-hierarquia-romanda-na-igreja');
const {applyEditorialEdits}=require(path.join(root,'.ia.rules/core/runtime/scripts/editorial-authoring.js'));
const original=fs.readFileSync(file,'utf8'),edits=[];
function para(prefix,replacement){const start=original.indexOf(prefix);if(start<0||original.indexOf(prefix,start+1)>=0)throw Error('Prefixo não unívoco: '+prefix);const end=original.indexOf('\n\n',start);if(end<0)throw Error('Fim ausente');edits.push({start,end,expected:original.slice(start,end),replacement,kind:'editorial',reason:'FT-112 M09b: alcance das novas inferências e fontes'});}
para('Os Judeus pós babilônia',`Depois do cativeiro babilônico, o temor de repetir a apostasia deu lugar, em muitos, a uma religiosidade exterior: o rigor das formas podia crescer enquanto faltavam amor e fidelidade. Ellen White descreve essa passagem do culto de imagens para a confiança nas cerimônias e nas exigências acrescentadas pelos homens.[^dtncativeiro] Não é um diagnóstico de cada judeu nem do judaísmo inteiro; é a advertência contra um desvio que também nos alcança. JESUS não condenou a obediência à lei de DEUS: denunciou a **hipocrisia**, a **incoerência** e as tradições que anulavam o mandamento.[^mc7] A questão não é trocar rigor por frouxidão. ELE foi explícito:`);
para('> ²³ …Ai de vocês',`> ²³ — Ai de vocês, mestres da lei e fariseus, **hipócritas**! Pois vocês dão o dízimo da hortelã, do endro e do cominho, mas têm negligenciado os preceitos mais importantes da lei: a **justiça**, a **misericórdia** e a **fidelidade**. Vocês devem praticar estas coisas **sem negligenciar aquelas**.
> — Bíblia, NVI. Mateus 23:23`);
para('Portanto o problema não era ser rigoroso',`Portanto, o problema não era obedecer rigorosamente ao que DEUS ordenou, mas ser **INCOERENTE**: exigir minúcias enquanto se desprezam justiça, misericórdia e fidelidade. **Praticar estas coisas SEM negligenciar aquelas.** O próprio texto distingue preceitos mais importantes; obedecer a todos não significa apagar essa hierarquia, muito menos santificar regras inventadas. Significa **NÃO escolher apenas o que nos convém**.`);
para('Agora, porém, a situação se inverteu.',`Agora, porém, vejo a reação inversa: para fugir do legalismo e do formalismo que também marcaram segmentos do judaísmo e do cristianismo, inclusive do catolicismo, passa-se a suspeitar da própria exigência de obedecer. Um erro serve de pretexto a outro. Há um precedente: Ellen White descreve como o desprezo ao judaísmo contribuiu para desfigurar a observância do sábado, num processo gradual que desembocou na exaltação do domingo.[^gcsabado] Não cabe reduzir esse desenvolvimento ao primeiro século, nem atribuí-lo indistintamente a todos os cristãos. O mecanismo que denuncio é este: tentando evitar a aparência de erros antigos, **abandonam-se verdades cruciais** da própria identidade. **Não é obra de um dia. São pequenas coisas.** O rebaixamento do Egito anunciado por Ezequiel e as transformações de Roma lembram que processos históricos não se encerram num instante; não afirmo que o Egito inteiro tenha virado literalmente um deserto nem que todo declínio romano cumpra uma única previsão.[^egitoroma] A velha história do sapo cozido lentamente serve aqui como **fábula**, não como demonstração zoológica. Assim se acumulam concessões: primeiro, “coisas secundárias”, consideradas não pecaminosas; depois, práticas mais graves ainda justificadas como inocentes; em seguida, “pecadinhos” e, finalmente, **“pecadões”**. Na leitura profética que proponho, a passagem da mulher perseguida de Apocalipse 12 à mulher perseguidora de Apocalipse 17 representa a corrupção da profissão religiosa: **a perseguição sofrida não imuniza contra tornar-se perseguidor**. Essa correspondência é interpretação, não uma afirmação textual de que sejam simplesmente a mesma mulher. A guerra contra o “restante da sua descendência” está em Apocalipse 12:17, antes das bestas do capítulo 13.[^ap1217] Dizer que “não há mais mulher para perseguir” é uma síntese retórica dessa leitura da apostasia, não prova de que a mulher protegida em 12:14–16 deixou de existir. O ponto que preservo é a distinção entre a profissão religiosa que se alia aos poderes perseguidores e o **remanescente fiel**.`);
para('O que se tem agora, é a igreja',`O que denuncio agora é uma igreja que, tentando fugir do formalismo e do legalismo, **perde a própria identidade**. Excessos reais não justificam o erro oposto. A experiência anterior à queda de Jerusalém e os desvios posteriores ao cativeiro nos advertem; a mensagem de Laodiceia denuncia nossa **mornidão**.[^ap3] Não devemos usar esses quadros como rótulos de todos os membros de um povo ou de uma época. Devemos reconhecer o mecanismo em nós: fugir da frouxidão para a hipocrisia, e da hipocrisia para a acomodação. Estamos em cima do muro, quando JESUS exige **praticar estas coisas sem negligenciar aquelas**.`);
para('1. A tentação ou provação possui',`1. A tentação é **comum à experiência humana**: não é uma exceção que autorize alguém a declarar inevitável sua derrota. “Comum” não significa banal, inofensiva ou necessariamente produzida apenas por seres humanos.
2. **DEUS é fiel** e providencia o escape para que seja possível suportar a tentação. A iniciativa e a garantia são DELE; a frase não exclui anjos ou outros instrumentos subordinados. O contraste decisivo é entre nossa insuficiência independente e **a fidelidade do poder que nos socorre**.`);
// O segundo item antigo forma parte do mesmo parágrafo da lista acima.
para('Logo, se é o próprio **DEUS**',`Logo, se é o próprio **DEUS** quem promete socorro, que homem, potestade, anjo ou demônio pode tornar impotente SUA promessa? Isso não elimina nossa liberdade de resistir à graça. **Não há desculpa para o pecado; nunca houve e nunca haverá.** JESUS fala do fogo eterno preparado para o diabo e seus anjos; os seres humanos não foram criados para a perdição.[^fogo] Tentar justificar o pecado é impossível: Ellen White o chama de intruso para cuja presença não se pode dar uma razão que o desculpe.[^gcpecado] No milênio, o juízo evidenciará a justiça de DEUS; os perdidos não serão vítimas de uma impossibilidade divina de salvá-los. “O destino dos ímpios se fixa por sua própria escolha.”[^gcescolha] A omissão também pode exprimir recusa diante da luz recebida; DEUS julga cada responsabilidade, não uma fórmula humana que ignore conhecimento e oportunidade.

Isso não exige uma **impecabilidade autossuficiente**, como se a criatura pudesse dispensar o CRIADOR, nem uma obediência produzida por coerção. No Céu, a fidelidade será livre e **nunca mais haverá pecado**.[^naum][^gcnaum] Não uso “impecabilidade” para negar essa promessa ou a pureza dos remidos: rejeito a ideia de independência moral de DEUS. A liberdade não obriga a repetição da rebelião. Nós, que, se DEUS quiser, estaremos lá e conheceremos o resultado do pecado, por que voltaríamos a ele? O Universo terá testemunhado sua natureza e suas consequências. A promessa é definitiva: **NINGUÉM NUNCA MAIS PECARÁ**. Essa segurança futura não decide a controvérsia, deixada em aberto nesta carta, sobre o momento de cessação do pecado antes do Advento.`);
para('Na compreensão adventista, vivemos, desde 1844,',`Na compreensão adventista, vivemos, desde 1844, **no grande Dia da Expiação** — o período ligado à obra de CRISTO no santuário celestial. Daniel registra: _“Até duas mil e trezentas tardes e manhãs; e o santuário será purificado.”_[^dn814] A ligação dessa profecia com 1844 foi desenvolvida na experiência dos pioneiros e exposta por Ellen White; a data não está escrita isoladamente no versículo.[^gc1844] Ela também declara: _“Vivemos hoje no grande dia da expiação.”_[^gc490] A conclusão é solene: **NÃO vivemos em um tempo comum**; não podemos viver **COMO SE** fosse comum.`);
para('> De <u>**igual** modo</u>',`> De **igual modo**, todos quantos desejem seja seu nome conservado no livro da vida, **devem**, agora, nos poucos dias de graça que restam, **afligir a alma** diante de Deus, em **tristeza pelo pecado** e em **arrependimento verdadeiro**. Deve haver um **exame de coração, profundo e fiel**. O espírito **leviano e frívolo**, alimentado por tantos cristãos professos, **deve ser deixado**.
> — Ellen G. White, O Grande Conflito - O grande juízo investigativo, p. 490`);
para('Essa é a aplicação apresentada:',`Essa é a aplicação apresentada: **arrependimento, humilhação, exame do coração, vigilância, pureza e consagração**. Minha aplicação é direta: não trocar essa tristeza pelo pecado por festividade, “confraternizações” ou entretenimentos que sirvam para abafar a consciência. Esse comentário é meu, não parte da citação. A crítica ao prazer e às atividades não essenciais dirige-se ao uso que alimenta a **frivolidade** — a distração que faz pouco caso do que é sério. O trecho não declara pecaminosa toda alegria ou atividade recreativa. Não se trata de abandonar irresponsavelmente o trabalho, mas de reproduzir espiritualmente a **SOLENIDADE** da ocasião. Se assim era no tipo, a cerimônia que servia de figura, que diremos de quem vive na realidade para a qual ela apontava?`);
para('Trata-se de **uma nova posição profética',`Trata-se de uma **nova posição profética**, uma **nova fase no ministério de CRISTO** e **responsabilidades proporcionais à luz recebida**. Ellen White escreve que, enquanto o juízo ocorre no Céu, _“deve haver uma **obra ESPECIAL de <u>PURIFICAÇÃO</u>**, ou de afastamento de pecado, entre o povo de Deus na Terra”_.[^gc425] **ESPECIAL**: relacionada à obra final de CRISTO, com a seriedade e a responsabilidade que isso exige. Santificação, obediência e pureza sempre foram necessárias. Mas Ellen White **NÃO diz apenas** que a velha obrigação cristã continua indiferente ao momento profético. A expressão “qual nunca houve”, se empregada como ênfase autoral, não pode ser inserida nessa passagem como palavras da autora, nem usada para inventar uma nova lei moral.`);
para('Portanto, as regras de conduta',`Portanto, a responsabilidade de quem recebeu essa luz **NÃO pode ser reduzida** à de quem ainda não a conhecia. A lei moral permanece; o conhecimento da obra celestial traz deveres que não se podem tratar como irrelevantes. Considere o paralelo com Pentecostes: a cerimônia previa santa convocação, e, antes do derramamento do ESPÍRITO, os discípulos perseveravam unidos em oração.[^pentecostes] A relação entre figura e cumprimento reclama **preparo e consagração**, não entretenimento que dissolva essa consciência. No grande Dia da Expiação, a urgência cresce porque a intercessão chegará ao fim. Viver deliberadamente contra a luz é incompatível com essa preparação. A figura do **joio** denuncia a falsa profissão; não nos dá competência para declarar infalivelmente o destino eterno de cada pessoa que avaliamos.[^joio] Ellen White afirma uma obra **ESPECIAL**, ligada ao ministério final de CRISTO no santuário. Essa distinção **NÃO pode ser apagada**:`);
para('Sabemos que Ellen White chama esta época',`Sabemos que Ellen White chama esta época de **grande Dia da Expiação**. Sabemos que ela afirma que essa luz trouxe **novos deveres**. Sabemos que ela exige uma **obra especial de PURIFICAÇÃO**. Então, como receber toda essa luz e viver como se ela nunca tivesse sido dada? Como usar a experiência de cristãos anteriores a 1844 como desculpa para desprezar responsabilidades agora conhecidas? O “qual nunca houve” de Daniel descreve a angústia anunciada; não é autorização para fabricar novas proibições morais.[^dn121] Mas tampouco podemos apagar a singularidade do momento e a gravidade da preparação. Seria racional? Seria coerente? Seria fé? Ellen White acrescenta:`);
para('Por si mesmos e em segredo, aplicam disciplina',`Por si mesmos e em segredo, aplicam disciplina como **SE** fossem a autoridade suprema. É precisamente isso que chamo de **romanismo** ou “hierarquia papal”: autoridade humana colocada acima da **VERDADE** e da consciência. Desprezam transparência, ordem, respeito, defesa e apuração, substituindo-os por suspeitas. A acusação é sobre esse **modo de agir**; não depende de afirmar que todas as estruturas históricas sejam idênticas. _Modus operandi_ é aqui minha expressão para esse procedimento, não uma citação literal atribuída a determinada tradução de *O Grande Conflito*.`);
para('E lembre-se, hoje é o tempo',`E lembre-se: o chamado exige mais que contentar-se com “não peques mais”.[^jo811] É preciso responder positivamente ao SENHOR: a **segunda milha** ensina a disposição de ir além do mínimo exigido.[^mt541] Isso já pertencia ao ensino de JESUS; a luz da expiação **aumenta nossa responsabilidade**, não inventa essa obediência positiva. Quando a igreja abandona solenidade, consagração e a obra de afastar o pecado e aquilo que alimenta um caráter leviano e frívolo, você e eu não estamos automaticamente inocentes. Se sabemos e, podendo cumprir nosso dever, consentimos ou nos omitimos, **também respondemos por isso**. A extensão de nossa responsabilidade acompanha a luz e a atuação que nos cabem. “Deve haver uma **obra ESPECIAL de PURIFICAÇÃO**”:[^gc425] a exigência está no testemunho; sua aplicação a cada conduta deve ser demonstrada, não imposta apenas pela opinião de quem escreve. **NÃO basta perguntar se é pecado: convém? Edifica?**[^1co1023]`);
const notes=`
[^dtncativeiro]: Ellen G. White, *O Desejado de Todas as Nações*, cap. 2, “O povo escolhido”, pp. 16–17 na paginação editorial do EPUB consultado. A autora distingue o abandono da idolatria, a obediência sem amor em muitos e o acréscimo humano de exigências.
[^mc7]: Bíblia, Marcos 7:6–13. A denúncia recai também sobre invalidar o mandamento de DEUS pela tradição; não só sobre observar seletivamente normas legítimas.
[^gcsabado]: Ellen G. White, *O Grande Conflito*, cap. 3, “Como começaram as trevas morais”, pp. 52–53. A passagem descreve a depreciação do sábado como instituição judaica e, em seguida, o decreto dominical de Constantino no século IV; não limita o processo ao século I.
[^egitoroma]: Bíblia, Ezequiel 29:14–15: rebaixamento do reino do Egito, não transformação de todo o país em deserto. Para o desenvolvimento gradual do poder religioso romano, cf. Ellen G. White, *O Grande Conflito*, cap. 3. A comparação desta carta é sobre processos graduais, não uma cronologia exaustiva de cumprimento.
[^ap1217]: Bíblia, ARA. Apocalipse 12:14–17; 13:1–18; 17:1–6. A expressão “restante da sua descendência” está em 12:17. A ligação proposta entre as duas mulheres é interpretação do autor, não identidade explicitamente declarada pelo texto.
[^fogo]: Bíblia, Mateus 25:41 e Apocalipse 20:10,14–15. Mateus diz “fogo eterno” preparado para o diabo e seus anjos; Apocalipse descreve o lago de fogo. A distinção evita apresentar as duas formulações como uma única citação literal. Cf. Ezequiel 33:11.
[^gcpecado]: Ellen G. White, *O Grande Conflito*, “Por que existe o sofrimento”, pp. 492–493. A impossibilidade de justificar a origem do pecado não impede compreender sua atuação, responsabilidade e resultado.
[^gcescolha]: Ellen G. White, *O Grande Conflito*, “É o homem imortal?”, p. 543; “Será desolada a Terra”, pp. 660–661. O primeiro trecho trata da escolha dos ímpios; o segundo, do julgamento durante o milênio. Cf. Bíblia, Tiago 4:17; Lucas 12:47–48.
[^naum]: Bíblia, Naum 1:9, no anúncio do juízo contra Nínive. A aplicação ao fim definitivo do pecado é explicitada por Ellen White no trecho indicado na nota seguinte.
[^gcnaum]: Ellen G. White, *O Grande Conflito*, “Por que existe o sofrimento”, p. 504: “Jamais o mal se manifestará de novo”; a autora cita Naum 1:9 e descreve uma criação experimentada que não voltará a desviar-se da fidelidade. Isso sustenta fidelidade permanente, não independência da criatura em relação a DEUS.
[^pentecostes]: Bíblia, Levítico 23:15–21; Atos 1:14; 2:1–4. A comparação é entre solenidade, preparação e cumprimento; não identifica Pentecostes com o Dia da Expiação nem transfere mecanicamente suas regras cerimoniais.
[^joio]: Bíblia, Mateus 13:24–30,36–43. CRISTO explica o destino do joio e do trigo; a parábola não torna infalíveis nossas classificações individuais.
[^jo811]: Bíblia, João 8:11. O mandamento de abandonar o pecado não esgota o ensino de CRISTO sobre amor, serviço e consagração.
[^mt541]: Bíblia, Mateus 5:41. A segunda milha é aplicada aqui como disposição de servir além do mínimo, preservado o contexto da ordem de JESUS.
`;
const result=applyEditorialEdits(original,edits),output=result.markedOutput+'\n'+notes;
fs.writeFileSync(file,output);const hash=s=>crypto.createHash('sha256').update(s).digest('hex');fs.writeFileSync(path.join(__dirname,'aplicacao-M09b.json'),JSON.stringify({before:hash(original),after:hash(output),regions:result.regions},null,2));console.log(edits.length+' regiões aplicadas.');
