const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'../../../..'),file=path.join(root,'_drafts/carta-aberta-hierarquia-romanda-na-igreja');
const {applyEditorialEdits}=require(path.join(root,'.ia.rules/core/runtime/scripts/editorial-authoring.js'));
const original=fs.readFileSync(file,'utf8'),edits=[];
function replace(expected,replacement){const start=original.indexOf(expected);if(start<0||original.indexOf(expected,start+1)>=0)throw Error('Trecho divergente: '+expected.slice(0,80));edits.push({start,end:start+expected.length,expected,replacement,kind:'editorial',reason:'FT-112 M09c: autoridade e hipótese institucional'});}
const a=original.indexOf('Ellen White escreveu: _“Deus ordenou'),b=original.indexOf('\n\n',a);
replace(original.slice(a,b),`Ellen White escreveu: _“Deus ordenou que os representantes de Sua igreja de todas as partes da Terra, quando reunidos numa Assembléia Geral, devam ter autoridade.”_[^t9261] A passagem trata da autoridade representativa da Associação Geral; não constitui, isoladamente, um regulamento das competências de cada comissão local. Também afirma: _“Deus investiu Sua igreja de especial autoridade e poder, por cuja desconsideração e desprezo ninguém se pode justificar; pois aquele que assim procede, despreza a voz de Deus.”_[^aa164] O contexto combate a **independência individual**, inclusive a de pastores e anciãos que pretendam substituir a Igreja. Se indivíduos usurpam a deliberação que compete à assembleia, estão em **FRONTAL CONTRADIÇÃO** com a ordem que dizem defender. A estrutura representativa não entrega soberania pessoal ao pastor — designado pelo campo, não eleito para esse posto pela congregação — nem aos anciãos. **A assembleia legitimamente constituída decide o que lhe compete**, dentro da respectiva jurisdição e das normas denominacionais; não recebe poder para contrariar as Escrituras. No caso da disciplina, a comissão não pode substituir a decisão da reunião administrativa.[^ordemlocal] Não se pode exigir submissão à ordem e, ao mesmo tempo, agir como dono dela.`);
replace('**Pelos frutos!**<adicionar footnote>','**Pelos frutos!**[^mt716]');
const c=original.indexOf('A possibilidade que interessa à argumentação permanece inteira:'),e=original.indexOf('\n\n',c);
replace(original.slice(c,e),`A possibilidade que interessa à argumentação permanece inteira: **escolas, universidades, hospitais, ADRA, ASA e congregações poderiam continuar funcionando enquanto o povo fiel fosse perseguido**. Minha convicção pessoal é forte: creio que estruturas desse valor continuarão em operação. Seu **valor social e econômico**, seus bens e a utilidade de sua **infraestrutura** sustentam essa expectativa. Não a transformo, porém, em revelação de que todas as entidades continuarão normalmente, nem afirmo que cada uma seja lucrativa. **A hipótese de continuidade institucional não precisa de um prazo inventado** para ser discutida.`);
replace('Enquanto isso, uma infraestrutura valiosa poderia e, provavelmente irá, permanecer ativa sob mãos infiéis.', 'Enquanto isso, uma infraestrutura valiosa poderia — e, na minha avaliação, provavelmente irá — permanecer ativa sob mãos infiéis.');
const result=applyEditorialEdits(original,edits);fs.writeFileSync(file,result.markedOutput+'\n[^ordemlocal]: Associação Geral, *Church Manual*, revisão de 2025, pp. 35–37,73–74,139. Pastores são designados pelo campo; disciplina exige deliberação da reunião administrativa e defesa do membro. [Manual oficial](https://gc.adventist.org/church-manual/).\n');
fs.writeFileSync(path.join(__dirname,'aplicacao-M09c.json'),JSON.stringify({regions:result.regions},null,2));
console.log(edits.length+' regiões aplicadas.');
