// Autor: JeanCarloEM.com
// Site do Autor: https://jeancarloem.com
// Repositorio: https://github.com/jcempro/agents.md
// Licenca: Mozilla Public License 2.0
// Site da Licenca: https://www.mozilla.org/MPL/2.0/
// Resumo da Licenca: uso, copia, modificacao e distribuicao permitidos conforme os termos da MPL-2.0.
// Disclaimer: fornecido AS IS, sem garantias de qualquer tipo.
// Gerado de: src/.ia.rules/core/runtime/scripts/autoupdate.ts; TypeScript 7.0.2 + esbuild 0.28.1; Node 24+.

const r=require("fs"),o=require("path"),l=require("child_process"),_=o.resolve(__dirname,"..","..","..",".."),w=o.join(__dirname,"update-agents.js");async function m(e=process.argv.slice(2),s={}){const n=s.rootDir||_,a=h(n);global.SOURCE_OWNER=a.upstreamRepository.split("/")[0],global.SOURCE_REPO=a.upstreamRepository.split("/")[1];const t=await A(a,n,async()=>require(w).main(e,s)),c=y(n,a);return c.changed&&(e.includes("--dry-run")||e.includes("--check"))?(console.log("migrate: package.json aliases para agent:autoupdate"),e.includes("--check")&&(process.exitCode=2)):c.changed&&!e.includes("--help")&&O(n,c),t}function y(e,s){const n=o.join(e,"package.json");if(!r.existsSync(n))throw new Error("PACKAGE_JSON_AUSENTE");const a=r.readFileSync(n,"utf8"),t=JSON.parse(a),c="npm run update:agents --",d={...t.scripts||{}};for(const E of["agent:autoupdate","agents:autoupdate","agent:agents","agents:update"])d[E]=c;const g={...t,agentsUpstream:s,agentsGovernance:{...t.agentsGovernance||{},schema:1,managedScriptPrefixes:Array.isArray(t.agentsGovernance&&t.agentsGovernance.managedScriptPrefixes)?t.agentsGovernance.managedScriptPrefixes:["agent:","shared:"],managedScripts:Array.isArray(t.agentsGovernance&&t.agentsGovernance.managedScripts)?t.agentsGovernance.managedScripts:["agents:autoupdate","agents:update","update:agents"],dependencies:Array.isArray(t.agentsGovernance&&t.agentsGovernance.dependencies)?t.agentsGovernance.dependencies:[],optionalDependencies:Array.isArray(t.agentsGovernance&&t.agentsGovernance.optionalDependencies)?t.agentsGovernance.optionalDependencies:[]},scripts:d},i=(a.match(/\n([ \t]+)"[^"]+"\s*:/u)||[null,"  "])[1],p=a.includes(`\r
`)?`\r
`:`
`,f=`${JSON.stringify(g,null,i).replace(/\n/gu,p)}${p}`;return{changed:S(a)!==S(f),content:f,packagePath:n}}function O(e,s){G(e),r.writeFileSync(s.packagePath,s.content,"utf8"),u(e,["add","--","package.json"]);const n=u(e,["diff","--cached","--name-only"]).stdout.trim().split(/\r?\n/u).filter(Boolean);if(n.length!==1||n[0]!=="package.json")throw new Error(`STAGING_MIGRACAO_INVALIDO:${n.join(",")}`);u(e,["commit","-m","ajuste: migra comando agent:autoupdate"]);const a=u(e,["branch","--show-current"]).stdout.trim();if(!a)throw new Error("BRANCH_ATUAL_AUSENTE");u(e,["push","-u","origin",a]),console.log("package.json migrado para agent:autoupdate.")}function G(e){const s=l.spawnSync("git",["-C",e,"diff","--quiet"],{encoding:"utf8"}),n=l.spawnSync("git",["-C",e,"diff","--cached","--quiet"],{encoding:"utf8"});if(s.status!==0||n.status!==0)throw new Error("WORKTREE_RASTREADO_SUJO_APOS_ATUALIZACAO")}function u(e,s){const n=l.spawnSync("git",["-C",e,...s],{encoding:"utf8"});if(n.status!==0)throw new Error(`git ${s.join(" ")} falhou: ${n.stderr||n.stdout}`);return n}function S(e){return String(e).replace(/\r\n/gu,`
`).trimEnd()}function h(e){const s=o.join(e,"package.json"),n=o.join(e,".ia.rules","core","update","upstream.json"),a=r.existsSync(n)?JSON.parse(r.readFileSync(n,"utf8")):{},t=r.existsSync(s)?JSON.parse(r.readFileSync(s,"utf8")).agentsUpstream||{}:{},c=a.schema===1?a:t;if(c.schema!==1||!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/u.test(String(c.upstreamRepository||"")))throw new Error("UPSTREAM_AGENTS_NAO_RESOLVIDO: metadado de sucessor ausente ou invalido.");return c}async function A(e,s,n){const a=o.join(s,".ia.rules","upstream.json");if(r.existsSync(a))return n();const t=r.existsSync,c=r.readFileSync,d=JSON.stringify({schema:1,upstreamRepository:e.upstreamRepository});r.existsSync=function(i){return o.resolve(String(i))===o.resolve(a)||t.call(r,i)},r.readFileSync=function(i,...p){return o.resolve(String(i))===o.resolve(a)?d:c.call(r,i,...p)};try{return await n()}finally{r.existsSync=t,r.readFileSync=c}}require.main===module&&m().catch(e=>{console.error(e.message),process.exitCode=e.exitCode||1});module.exports={main:m,planPackageMigration:y,readSuccessorPolicy:h,withVirtualUpstream:A};
