// Autor: JeanCarloEM.com
// Site do Autor: https://jeancarloem.com
// Repositorio: https://github.com/jcempro/agents.md
// Licenca: Mozilla Public License 2.0
// Site da Licenca: https://www.mozilla.org/MPL/2.0/
// Resumo da Licenca: uso, copia, modificacao e distribuicao permitidos conforme os termos da MPL-2.0.
// Disclaimer: fornecido AS IS, sem garantias de qualquer tipo.
// Gerado de: src/.ia.rules/core/runtime/scripts/long-running.ts; TypeScript 7.0.2 + esbuild 0.28.1; Node 24+.

const F=require("child_process"),L=require("crypto"),m=require("fs"),g=require("os"),b=require("path");function S(t,r){if(!t.length)return 0;const e=[...t].map(Number).filter(Number.isFinite).sort((n,i)=>n-i);return e[Math.min(e.length-1,Math.max(0,Math.ceil(e.length*r)-1))]||0}function y(t,r={}){const e=Number.isFinite(r.margin)?r.margin:.5,n=Number.isFinite(r.minimumMs)?r.minimumMs:1e3,i=Number.isFinite(r.maximumMs)?r.maximumMs:36e5,s=S(t,.95)||n;return Math.min(i,Math.max(n,Math.ceil(s*(1+e))))}function _(t,r={}){const e=Number.isFinite(r.initialMs)?Math.max(250,r.initialMs):500,n=Number.isFinite(r.maximumMs)?Math.max(e,r.maximumMs):3e4,i=Number.isInteger(r.maximumAttempts)?Math.max(1,r.maximumAttempts):8;return!Number.isInteger(t)||t<0||t>=i?null:Math.min(n,e*2**t)}function O(t){if(!Number.isInteger(t)||t<=0)return!1;try{return process.kill(t,0),!0}catch(r){return r.code==="EPERM"}}function M(t,r){m.mkdirSync(b.dirname(t),{recursive:!0});const e=`${t}.tmp-${process.pid}-${L.randomBytes(3).toString("hex")}`;m.writeFileSync(e,`${JSON.stringify(r,null,2)}
`,{encoding:"utf8",flag:"wx"}),m.renameSync(e,t)}function N(t,r=[],e={}){const n=new Date().toISOString(),i=Date.now(),s=e.statePath,x=e.timeoutMs||y(e.history||[]),f={schema:"agents-long-run/v1",command:t,args:r,startedAt:n,timeoutMs:x,environment:{platform:g.platform(),release:g.release(),arch:g.arch(),node:process.version},status:"running"};return new Promise((P,v)=>{const u=F.spawn(t,r,{cwd:e.cwd||process.cwd(),env:e.env||process.env,shell:!1,stdio:e.stdio||"ignore",windowsHide:!0});f.pid=u.pid||null,s&&M(s,f);let w=!1;const o=(a,c,h)=>{if(w)return;w=!0,clearTimeout(A),e.signal&&e.signal.removeEventListener("abort",d);const l={...f,status:a,exitCode:Number.isInteger(c)?c:null,endedAt:new Date().toISOString(),durationMs:Date.now()-i};h&&(l.error=h.message||String(h)),s&&M(s,l),a==="completed"?P(l):v(Object.assign(new Error(`LONG_RUN_${a.toLocaleUpperCase("en-US")}`),{result:l}))},d=()=>{u.kill(),o("cancelled",null)},A=setTimeout(()=>{u.kill(),o("timed_out",null)},x);u.once("error",a=>o("failed",null,a)),u.once("exit",(a,c)=>o(a===0?"completed":"failed",a,c?new Error(`signal:${c}`):void 0)),e.signal&&(e.signal.aborted?d():e.signal.addEventListener("abort",d,{once:!0}))})}function E(t,r=[],e={}){if(!e.statePath||!m.existsSync(e.statePath))return N(t,r,e);const n=JSON.parse(m.readFileSync(e.statePath,"utf8"));if(n.status==="completed"&&n.command===t&&JSON.stringify(n.args)===JSON.stringify(r))return Promise.resolve({...n,resumed:!1,reused:!0});if(n.status==="running"&&O(n.pid))return Promise.reject(Object.assign(new Error("LONG_RUN_ALREADY_ACTIVE"),{result:n}));const i=n.status==="running"?"orphaned":n.status;return N(t,r,{...e,history:[...e.history||[],n.durationMs].filter(Number.isFinite)}).then(s=>({...s,resumed:!0,previousStatus:i}))}async function I(t=process.argv.slice(2)){const r=t.indexOf("--");if(r<1)throw new Error("Uso: long-running <state.json> -- <comando> [args]");const e=b.resolve(t[0]),n=t[r+1];if(!n)throw new Error("LONG_RUN_COMANDO_AUSENTE");const i=await E(n,t.slice(r+2),{statePath:e,stdio:"inherit"});console.log(JSON.stringify(i))}require.main===module&&I().catch(t=>{console.error(t.message),process.exitCode=1});module.exports={boundedBackoff:_,deriveTimeout:y,percentile:S,processExists:O,resumeLongProcess:E,runLongProcess:N,writeState:M};
