// Autor: JeanCarloEM.com
// Site do Autor: https://jeancarloem.com
// Repositorio: https://github.com/jcempro/agents.md
// Licenca: Mozilla Public License 2.0
// Site da Licenca: https://www.mozilla.org/MPL/2.0/
// Resumo da Licenca: uso, copia, modificacao e distribuicao permitidos conforme os termos da MPL-2.0.
// Disclaimer: fornecido AS IS, sem garantias de qualquer tipo.
// Gerado de: src/.ia.rules/core/runtime/scripts/rcf-trace.ts; TypeScript 7.0.2 + esbuild 0.28.1; Node 24+.

const P=require("child_process"),g=require("crypto"),m=require("fs"),d=require("path"),x="agents-rcf-trace/v1",I="[PENDENTE-CODIGO]",v=/\[([a-f0-9]{7})\]$/iu;function V(e=__dirname){let t=d.resolve(e);for(;d.dirname(t)!==t;){if(m.existsSync(d.join(t,"AGENTS.md"))&&m.existsSync(d.join(t,"package.json")))return t;t=d.dirname(t)}throw new Error("RAIZ_REPOSITORIO_NAO_ENCONTRADA")}function y(e,t,n={}){const r=P.spawnSync("git",t,{cwd:e,encoding:"utf8",shell:!1});if(!n.optional&&r.status!==0)throw new Error(`GIT_FALHOU:${t.join(" ")}:${r.stderr||r.stdout}`);return r}function O(e,t){return new Set(y(e,["show","--pretty=","--name-only","--format=",t]).stdout.split(/\r?\n/u).filter(Boolean))}function w(e,t){return g.createHash("sha256").update(`${e}\0${h(t).trim()}`,"utf8").digest("hex").slice(0,24)}function h(e){return String(e).replace(/\s+(?:\[PENDENTE-CODIGO\]|\[[a-f0-9]{7}\])$/iu,"")}function $(e,t){const n=h(e).trim();return t||!n||/^(?:#|<!--|\||```|~~~)/u.test(n)||/^\[[^\]]+\]:/u.test(n)?!1:/\b(?:DEVE|DEVEM|NÃO DEVE|NÃO DEVEM|PODE|PODEM|PROIBID[OA]S?|OBRIGATÓRI[OA]S?|obrigatório|proibido)\b/iu.test(n)}function N(e){const t=String(e).replace(/\r\n/gu,`
`).split(`
`),n=[];let r=!1;for(let s=0;s<t.length;s+=1){if(/^\s*(?:```|~~~)/u.test(t[s])){r=!r;continue}$(t[s],r)&&n.push({index:s,text:t[s]})}return{lines:t,material:n}}function S(e,t=C(e)){if(!m.existsSync(t))return{format:x,schema:1,entries:[]};let n;try{n=JSON.parse(m.readFileSync(t,"utf8"))}catch(r){throw new Error(`RCF_MAPA_INVALIDO:${r.message}`)}if(!n||n.format!==x||n.schema!==1||!Array.isArray(n.entries))throw new Error("RCF_MAPA_INVALIDO");return n}function C(e){return d.join(e,".ia.rules","state","traceability","rcf-map.json")}function R(e,t){m.mkdirSync(d.dirname(e),{recursive:!0});const n=`${e}.agents-${process.pid}.tmp`;try{m.writeFileSync(n,`${JSON.stringify(t,null,2)}
`,"utf8"),m.renameSync(n,e)}finally{m.existsSync(n)&&m.rmSync(n,{force:!0})}}function b(e,t){const n=y(e,["blame","--line-porcelain","--",t]),r=[];for(const s of n.stdout.split(/\r?\n/u)){const f=/^([a-f0-9]{40})\s+\d+\s+\d+(?:\s+\d+)?$/u.exec(s);f&&r.push(f[1])}return r}function F(e,t,n={}){if(!n.constructorNormative)throw new Error("MIGRACAO_RCF_EXIGE_CONSTRUCTOR_NORMATIVE");const r=d.join(e,t),s=N(m.readFileSync(r,"utf8")),f=b(e,t);if(f.length!==s.lines.length-1&&f.length!==s.lines.length)throw new Error(`RCF_BLAME_INCOMPATIVEL:lines=${s.lines.length}:hashes=${f.length}`);const o=S(e,n.mapPath),u=new Map(o.entries.map(c=>[c.id,c]));for(const c of s.material){const i=f[c.index];if(!i)throw new Error(`RCF_BLAME_AUSENTE:${t}:${c.index+1}`);s.lines[c.index]=`${h(c.text)} [${i.slice(-7)}]`;const l=w(t,c.text);u.set(l,{artifacts:[t],commit:i,ft:n.ft||"",id:l,line:c.index+1,rcf:t,sentenceSha256:g.createHash("sha256").update(h(c.text).trim(),"utf8").digest("hex"),state:"synchronized",syncCommit:""})}return m.writeFileSync(r,s.lines.join(`
`),"utf8"),o.entries=[...u.values()].sort((c,i)=>c.rcf.localeCompare(i.rcf,"en")||c.line-i.line),R(n.mapPath||C(e),o),{entries:s.material.length,rcf:t}}function M(e,t,n,r={}){if(!n.length)throw new Error("RCF_ARTEFATO_AUSENTE");const s=d.join(e,t),f=N(m.readFileSync(s,"utf8")),o=new Set((r.lines||[]).map(Number));if(!o.size)throw new Error("RCF_LINHA_MATERIAL_AUSENTE");const u=S(e,r.mapPath),c=new Map(u.entries.map(i=>[i.id,i]));for(const i of f.material.filter(l=>o.has(l.index+1))){f.lines[i.index]=`${h(i.text)} ${I}`;const l=w(t,i.text);c.set(l,{artifacts:n.map(a=>a.replace(/\\/gu,"/")).sort(),commit:"",ft:r.ft||"",id:l,line:i.index+1,rcf:t,sentenceSha256:g.createHash("sha256").update(h(i.text).trim(),"utf8").digest("hex"),state:"pending",syncCommit:""})}return m.writeFileSync(s,f.lines.join(`
`),"utf8"),u.entries=[...c.values()].sort((i,l)=>i.rcf.localeCompare(l.rcf,"en")||i.line-l.line),R(r.mapPath||C(e),u),{pending:o.size}}function T(e,t,n={}){const r=y(e,["rev-parse",`${t}^{commit}`]).stdout.trim(),s=O(e,r),f=n.mapPath||C(e),o=S(e,f),u=o.entries.filter(i=>i.state==="pending");if(!u.length)throw new Error("RCF_PENDENCIA_AUSENTE");const c=new Map;for(const i of u){if(!i.artifacts.some(l=>s.has(l)))throw new Error(`RCF_COMMIT_SEM_ARTEFATO_CAUSAL:${i.id}`);c.has(i.rcf)||c.set(i.rcf,[]),c.get(i.rcf).push(i)}for(const[i,l]of c){const a=d.join(e,i),_=N(m.readFileSync(a,"utf8"));for(const E of l){const p=_.material.find(A=>w(i,A.text)===E.id);if(!p||!p.text.trimEnd().endsWith(I))throw new Error(`RCF_PENDENCIA_DIVERGENTE:${E.id}`);_.lines[p.index]=`${h(p.text)} [${r.slice(-7)}]`,E.commit=r,E.state="synchronized"}m.writeFileSync(a,_.lines.join(`
`),"utf8")}return R(f,o),{commit:r,synchronized:u.length}}function D(e,t={}){const n=S(e,t.mapPath),r=new Map,s=new Map;for(const o of n.entries){if(!o.id||!o.rcf||!o.sentenceSha256||!Array.isArray(o.artifacts)||!["pending","materialized","synchronized"].includes(o.state))throw new Error(`RCF_ENTRADA_INVALIDA:${o.id||"sem-id"}`);r.has(o.rcf)||r.set(o.rcf,[]),r.get(o.rcf).push(o)}let f=0;for(const[o,u]of r){const c=N(m.readFileSync(d.join(e,o),"utf8"));f+=c.material.length;for(const i of c.material){const l=w(o,i.text),a=u.find(A=>A.id===l);if(!a)throw new Error(`RCF_SENTENCA_NAO_MAPEADA:${o}:${i.index+1}`);if(g.createHash("sha256").update(h(i.text).trim(),"utf8").digest("hex")!==a.sentenceSha256)throw new Error(`RCF_SENTENCA_DIVERGENTE:${a.id}`);if(a.state==="pending"){if(!i.text.trimEnd().endsWith(I)||a.commit)throw new Error(`RCF_PENDENCIA_INVALIDA:${a.id}`);continue}const E=v.exec(i.text.trimEnd());if(!E||!/^[a-f0-9]{40}$/u.test(a.commit)||E[1].toLocaleLowerCase("en-US")!==a.commit.slice(-7))throw new Error(`RCF_ASSINATURA_INVALIDA:${a.id}`);s.has(a.commit)||(y(e,["cat-file","-e",`${a.commit}^{commit}`]),s.set(a.commit,O(e,a.commit)));const p=s.get(a.commit);if(!a.artifacts.some(A=>p.has(A)))throw new Error(`RCF_CAUSALIDADE_INVALIDA:${a.id}`)}}return{entries:n.entries.length,material:f}}function j(e){const t={artifacts:[],lines:[]};for(let n=1;n<e.length;n+=1){const r=e[n];r==="--constructor-normative"?t.constructorNormative=!0:["--artifact","--line"].includes(r)?t[r==="--artifact"?"artifacts":"lines"].push(e[++n]):r.startsWith("--")&&(t[r.slice(2)]=e[++n])}return t}function L(e=process.argv.slice(2),t={}){const n=t.rootDir||V(),r=e[0]||"validate",s=j(e),f=s.rcf||"RCF.md";if(r==="migrate")return F(n,f,{constructorNormative:s.constructorNormative,ft:s.ft});if(r==="prepare")return M(n,f,s.artifacts,{ft:s.ft,lines:s.lines});if(r==="finalize")return T(n,s.commit||"",{});if(r==="validate")return D(n,{});throw new Error(`RCF_COMANDO_INVALIDO:${r}`)}if(require.main===module)try{process.stdout.write(`${JSON.stringify(L())}
`)}catch(e){process.stderr.write(`${e.message}
`),process.exitCode=1}module.exports={finalize:T,isMaterialLine:$,main:L,materialLines:N,migrateConstructor:F,prepare:M,sentenceId:w,stripMarker:h,validate:D};
