// Autor: JeanCarloEM.com
// Site do Autor: https://jeancarloem.com
// Repositorio: https://github.com/jcempro/agents.md
// Licenca: Mozilla Public License 2.0
// Site da Licenca: https://www.mozilla.org/MPL/2.0/
// Resumo da Licenca: uso, copia, modificacao e distribuicao permitidos conforme os termos da MPL-2.0.
// Disclaimer: fornecido AS IS, sem garantias de qualquer tipo.
// Gerado de: src/.ia.rules/core/runtime/scripts/to-ia.ts; TypeScript 7.0.2 + esbuild 0.28.1; Node 24+.

const T=require("crypto"),_=require("child_process"),O=require("fs"),p=require("path"),{loadConfiguration:I}=require("./configuration"),b=p.resolve(__dirname,"..","..","..",".."),y=I(b),U=p.join(b,".ia.rules","cache","outputs"),v=y.output.maxBytes,S=y.output.maxLines,w=["fatal","error","warning","change","result","metric","info","debug"];function E(e){return String(e||"").replace(/\r\n?/gu,`
`).replace(/\x1B\[[0-?]*[ -/]*[@-~]/gu,"").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/gu,"")}function x(e){return/\b(fatal|panic)\b/iu.test(e)?"fatal":/\b(error|erro|exception|falhou|failure)\b/iu.test(e)?"error":/\b(warning|warn|aviso)\b/iu.test(e)?"warning":/\b(changed|change|alterad[oa]|cri(?:ad[oa]|ou)|removid[oa])\b/iu.test(e)?"change":/\b(ok|success|resultado|result)\b/iu.test(e)?"result":/\b(metric|total|bytes|lines|tempo|ms)\b/iu.test(e)?"metric":/\b(debug|trace|verbose)\b/iu.test(e)?"debug":"info"}function L(e){return`TO_IA_${e.toUpperCase()}`}function B(e){return e.map((r,t)=>({...r,index:t})).sort((r,t)=>w.indexOf(r.level)-w.indexOf(t.level)||r.index-t.index).map(({index:r,...t})=>t)}function C(e){const r=[];let t=null,s=0;for(const n of e){if(n===t){s+=1;continue}s>0&&r.push(`[to-ia: linha anterior repetida ${s} vez(es)]`),r.push(n),t=n,s=0}return s>0&&r.push(`[to-ia: linha anterior repetida ${s} vez(es)]`),r}function A(e,r){const t=T.createHash("sha256").update(r,"utf8").digest("hex"),s=new Date().toISOString().replace(/[-:TZ.]/gu,"").slice(0,14).replace(/^(\d{8})(\d{6})$/u,"$1.$2"),n=String(e||"command").replace(/[^A-Za-z0-9._-]/gu,"-"),o=p.posix.join(".ia.rules","cache","outputs",`${s}-${n}-${t.slice(0,12)}.log`),c=p.join(b,o);return O.mkdirSync(p.dirname(c),{recursive:!0}),O.writeFileSync(c,r,"utf8"),{path:o,sha256:t}}function $(e,r){const t=[];let s=!1,n=Buffer.byteLength(`${JSON.stringify(r)}
`,"utf8");for(const o of e){if(t.length>=S-1)break;const c=JSON.stringify(o),u=v-n-1;if(u<=0)break;if(Buffer.byteLength(c,"utf8")>u){const f=" [truncated]";let i=o.message;for(;i&&Buffer.byteLength(JSON.stringify({...o,code:"TO_IA_TRUNCATED",message:`${i}${f}`}),"utf8")>u;)i=i.slice(0,-1);if(!i)break;const d={...o,code:"TO_IA_TRUNCATED",message:`${i}${f}`};t.push(d),n+=Buffer.byteLength(`${JSON.stringify(d)}
`,"utf8"),s=!0;break}t.push(o),n+=Buffer.byteLength(`${c}
`,"utf8")}return{shown:t,shortened:s}}function h({command:e="agent:filter",exit:r=0,stderr:t="",stdout:s=""}={}){const n=E(`${s}${t?`
${t}`:""}`),o=C(n.split(`
`).filter(Boolean)),c=B(o.map(a=>({code:L(x(a)),level:x(a),message:a}))),u=c.filter(a=>a.level!=="debug"),f={v:1,command:e,status:r===0?"ok":"error",exit:r,totalLines:o.length,totalBytes:Buffer.byteLength(n,"utf8"),shown:0,truncated:!1,artifact:"",sha256:T.createHash("sha256").update(n,"utf8").digest("hex")},i=$(u,f),d=i.shown.length!==u.length||c.length!==u.length||i.shortened,g=d?A(e,n):null,l={...f,shown:i.shown.length,truncated:d,artifact:g?g.path:"",sha256:g?g.sha256:f.sha256},m=$(u,l);if(l.shown=m.shown.length,l.truncated=d||m.shown.length!==u.length||m.shortened,l.truncated&&!l.artifact){const a=A(e,n);l.artifact=a.path,l.sha256=a.sha256}return`${[l,...m.shown].map(a=>JSON.stringify(a)).join(`
`)}
`}function N(e){const r={command:"agent:filter",exit:0};for(let t=0;t<e.length;t+=1){const s=e[t];if(s==="--help")r.help=!0;else if(s==="--command"){if(r.command=e[++t]||"",!r.command)throw new Error("PARAMETRO_NORMATIVO_AUSENTE:command")}else if(s==="--exit"){if(r.exit=Number(e[++t]),!Number.isInteger(r.exit))throw new Error("PARAMETRO_INVALIDO:exit")}else if(s==="--run"){r.run=e.slice(t+1);break}else throw new Error(`PARAMETRO_INVALIDO:${s}`)}return r}function R(){return`Uso: node to-ia.js [--command <nome>] [--exit <codigo>] [--run <comando> [args...]]
`}if(require.main===module){let e;try{e=N(process.argv.slice(2))}catch(t){process.stdout.write(h({exit:2,stderr:t.message})),process.exitCode=2;return}if(e.help){process.stdout.write(R());return}if(e.run){const[t,...s]=e.run;if(!t)process.stdout.write(h({...e,exit:2,stderr:"PARAMETRO_NORMATIVO_AUSENTE:command"})),process.exitCode=2;else{const n=_.spawnSync(t,s,{cwd:b,encoding:"utf8",shell:!1});process.stdout.write(h({command:e.command==="agent:filter"?`to-ia:${t}`:e.command,exit:Number.isInteger(n.status)?n.status:1,stderr:`${n.stderr||""}${n.error?`
${n.error.message}`:""}`,stdout:n.stdout||""})),process.exitCode=Number.isInteger(n.status)?n.status:1}return}let r="";process.stdin.setEncoding("utf8"),process.stdin.on("data",t=>{r+=t}),process.stdin.on("end",()=>{process.stdout.write(h({...e,stdout:r}))})}module.exports={filterOutput:h,help:R,normalize:E,parseArgs:N};
