// Autor: JeanCarloEM.com
// Site do Autor: https://jeancarloem.com
// Repositorio: https://github.com/jcempro/agents.md
// Licenca: Mozilla Public License 2.0
// Site da Licenca: https://www.mozilla.org/MPL/2.0/
// Resumo da Licenca: uso, copia, modificacao e distribuicao permitidos conforme os termos da MPL-2.0.
// Disclaimer: fornecido AS IS, sem garantias de qualquer tipo.
// Gerado de: src/.ia.rules/core/runtime/scripts/todo-intake.ts; TypeScript 7.0.2 + esbuild 0.28.1; Node 24+.

const v=require("crypto"),V=require("child_process"),a=require("fs"),I=require("os"),d=require("path"),_=d.join(".ia.rules","state","TODO.ia.md"),w=d.join(".ia.rules","state","history"),z=d.join(".ia.rules","state","FT.implementados.md");function j(t,e={}){const i=D(t,e).map(o=>{const l=d.join(t,o),s=a.readFileSync(l,"utf8");return{hash:p(s),items:R(s),path:A(o)}}),r=i.find(o=>o.path===A(_)),c=r&&i.some(o=>o.path!==r.path&&o.hash!==r.hash);return{code:i.length?"TODO_IA_FOUND":"TODO_IA_EMPTY",records:i,status:!r||c?"triagem_requerida":"ok"}}function k(t,e={}){const n=j(t,e),i=n.records.filter(r=>r.path!==A(_)||r.items.some(c=>c.status==="pendente"));if(i.length)throw new Error(`TODO_IA_TRIAGEM_PENDENTE:${i.map(r=>r.path).join(",")}`);return n}function D(t,e={}){const n=[e.path||_,"TODO.ia.md"].map(i=>d.normalize(String(i)));return[...new Set(n)].filter(i=>!d.isAbsolute(i)&&a.existsSync(d.join(t,i))).sort((i,r)=>A(i).localeCompare(A(r),"en"))}function R(t){return String(t).split(/\r?\n/u).map((e,n)=>({line:e,number:n+1})).filter(e=>/^\s*[-*]\s+(?:\[[ xX-]\]\s+)?\S/u.test(e.line)).map(e=>({line:e.number,status:/\[[xX]\]/u.test(e.line)?"concluido":"pendente",text:e.line.replace(/^\s*[-*]\s+(?:\[[ xX-]\]\s+)?/u,"").trim()}))}const U="# TO-DOs",b="- [ ] Equalizar e executar as TO-DOs como frentes convergentes de um único objetivo",M=new Set(["⬜","📌","📜","⚖️","⏳","🔄","🔎","✅"]);function y(t){const e=String(t||"").replace(/\r\n/gu,`
`),n=e.indexOf(`
${U}
`);if(!e.startsWith(`# RCF — Governança da TO-DO
`)||n<0)throw new Error("TODO_GOVERNANCA_INVALIDA");const i=e.slice(0,n+1),r=e.slice(n+1);if(!i.includes(b))throw new Error("TODO_EQUALIZER_AUSENTE");const c=[];for(const[o,l]of r.split(`
`).entries()){if(/^\s+[-*]\s+(?:\[[ xX]\]|[⬜📌📜⚖️⏳🔄🔎✅])/u.test(l))continue;const s=l.match(/^- \[([ xX])\] (\S.*)$/u),h=l.match(/^([⬜📌📜⚖️⏳🔄🔎✅]) (\S.*)$/u);if(!s&&!h)continue;const O=s?s[1].toLocaleLowerCase()==="x"?"✅":"⬜":h[1];c.push({line:o+i.split(`
`).length,marker:s?"checkbox":"emoji",status:O,text:(s?s[2]:h[2]).trim()})}if(c.some(o=>o.text.startsWith("Equalizar e executar")&&(o.marker!=="checkbox"||o.status!=="⬜")))throw new Error("TODO_EQUALIZER_NAO_PERENE");return{governanceHash:p(i),operationalHash:p(r),roots:c}}function P(t){const e=d.join(t,"TODO.ia.md");if(!a.existsSync(e))throw new Error("TODO_RAIZ_AUSENTE");const n=a.readFileSync(e,"utf8"),i=y(n),r=d.join(t,".ia.rules","state");a.mkdirSync(r,{recursive:!0});const c=d.join(t,".ia.rules","continue.ia"),o=d.join(r,"continue.ia");if(!a.existsSync(c)&&!a.existsSync(o))throw new Error("CONTINUE_IA_AUSENTE");const l=a.readFileSync(a.existsSync(o)?o:c,"utf8");if(a.existsSync(o)&&a.existsSync(c)&&p(a.readFileSync(c,"utf8"))!==p(l))throw new Error("CONTINUE_MIGRACAO_CONFLITO");E(o,l);const s=d.join(t,_);if(a.existsSync(s)&&p(a.readFileSync(s,"utf8"))!==p(n))throw new Error("TODO_MIGRACAO_CONFLITO");E(s,n);const h={"memory.md":`# Memória operacional

Índice durável; evidência não constitui autoridade.
`,"fix.md":`# Correções

Índice de riscos e reclamações do desenvolvedor.
`,"FT.implementados.md":`# FTs implementadas

Índice mínimo para pedidos e evidências canônicas.
`};for(const[u,m]of Object.entries(h)){const T=d.join(r,u);a.existsSync(T)||E(T,m)}const O={schema:"agents-state-migration/v1",generatedAt:new Date().toISOString(),entries:[{source:"TODO.ia.md",destination:".ia.rules/state/TODO.ia.md",sha256:p(n)},{source:".ia.rules/continue.ia",destination:".ia.rules/state/continue.ia",sha256:p(l)}]};E(d.join(r,"migration-baseline.json"),`${JSON.stringify(O,null,2)}
`);const f={schema:"agents-state-index/v1",active:"continue.ia",todo:"TODO.ia.md",durable:"memory.md",corrections:"fix.md",completed:"FT.implementados.md",governanceHash:i.governanceHash};return E(d.join(r,"index.json"),`${JSON.stringify(f,null,2)}
`),{code:"STATE_MIGRATED",baseline:O,index:f}}function N(t){const e=d.join(t,".ia.rules","state"),n=d.join(t,_),i=d.join(e,"continue.ia");if(!a.existsSync(n)||!a.existsSync(i))throw new Error("ESTADO_CANONICO_INCOMPLETO");const r=a.readFileSync(n,"utf8"),c=y(r).governanceHash,o=d.join(t,"TODO.ia.md");if(a.existsSync(o)&&y(a.readFileSync(o,"utf8")).governanceHash!==c)throw new Error("TODO_GOVERNANCA_DIVERGENTE");return E(o,r),E(d.join(t,".ia.rules","continue.ia"),a.readFileSync(i,"utf8")),{code:"STATE_PROJECTIONS_SYNCED",todoHash:p(r),continueHash:p(a.readFileSync(i,"utf8"))}}function G(t,e,n,i={}){const r=d.join(t,_);if(!a.existsSync(r))throw new Error("TODO_CANONICO_AUSENTE");const o=a.readFileSync(r,"utf8").replace(/\r\n/gu,`
`).split(`
`),l=o.indexOf(U),s=/^(?:- \[[ xX]\]|[⬜📌📜⚖️⏳🔄🔎✅]) (\S.*)$/u,h=o.map((m,T)=>({index:T,match:m.match(s)})).filter(m=>m.index>l&&m.match),O=h.filter(m=>m.match[1]===e);if(O.length!==1)throw new Error(`TODO_FRENTE_NAO_UNICA:${e}`);const f=O[0],u=f.match[0].startsWith("- [")?/^- \[[xX]\]/u.test(f.match[0])?"✅":"⬜":f.match[0].match(/^[⬜📌📜⚖️⏳🔄🔎✅]/u)[0];if(i.approvedHuman){if(i.authorization!=="human"||u!=="✅")throw new Error("TODO_REMOCAO_SEM_APROVACAO");const m=h.find(T=>T.index>f.index);o.splice(f.index,(m?m.index:o.length)-f.index)}else{if(!M.has(n))throw new Error(`TODO_STATUS_INVALIDO:${n}`);if(n==="⏳"&&(i.authorization!=="human"||i.normativeFtConcluded!==!0))throw new Error("TODO_IMPLEMENTACAO_NAO_AUTORIZADA");o[f.index]=`${n} ${e}`}return E(r,o.join(`
`)),N(t),{code:i.approvedHuman?"TODO_ROOT_REMOVED":"TODO_ROOT_TRANSITIONED",from:u,to:i.approvedHuman?null:n,text:e}}function J(t,e,n={}){if(n.authorization!=="human")throw new Error("FT_CONCLUSAO_NAO_AUTORIZADA");const i=d.join(t,".ia.rules","state","continue.ia");if(!a.existsSync(i))throw new Error("CONTINUE_CANONICO_AUSENTE");let r=a.readFileSync(i,"utf8").replace(/\r\n/gu,`
`);const c=n.timestamp||new Date().toISOString();for(const s of e){const h=s.replace(/[.*+?^${}()|[\]\\]/gu,"\\$&"),O=r.match(new RegExp(`^${h}\\|`,"mu"));if(!O)throw new Error(`FT_ESTADO_AUSENTE:${s}`);const f=O.index,m=r.slice(f).search(/\nFT-\d+\|/u),T=m<0?r.length:f+m+1;let S=r.slice(f,T).replace(/\|status=[^|\r\n]+/u,"|status=concluida").replace(/\|atualizacao=[^|\r\n]+/u,`|atualizacao=${c}`).replace(/\[(?:pendente|em_andamento)\]/gu,"[concluido]");/\|autorizacao=/u.test(S.split(`
`,1)[0])||(S=S.replace(/\n/u,`|autorizacao=humana
`)),/\|conclusao=/u.test(S.split(`
`,1)[0])||(S=S.replace(/\n/u,`|conclusao=${c}
`)),S=S.replace(/^resultado=.*\nverificacoes=.*\npendencias=.*\n\n(?=objetivo=)/mu,"");const g=n.evidence&&n.evidence[s]||{},F=`resultado=${g.result||"Implementação concluída conforme aceite da FT."}
verificacoes=${g.verification||"Gates locais aplicáveis executados."}
pendencias=${g.pending||"Nenhuma pendência funcional; validação humana do TODO permanece externa."}`;S=/^pendencias=.*$/mu.test(S)?S.replace(/^pendencias=.*$/mu,F):`${S.trimEnd()}
${F}
`,r=`${r.slice(0,f)}${S}${r.slice(T)}`}E(i,r);const o=n.developerValidated===!0?{validated:e,pendingValidation:[]}:{validated:[],pendingValidation:e},l=H(t,o,{authorization:n.authorization,validatedBy:n.developerValidated===!0?"developer":""});return{code:"FT_STATE_CONCLUDED",ids:e,reconciliation:l}}function x(t){const e=String(t||"").replace(/\r\n/gu,`
`),n=[...e.matchAll(/^FT-\d+\|.*$/gmu)],i=n.map((c,o)=>{const l=c.index,s=o+1<n.length?n[o+1].index:e.length,h=e.slice(l,s).trimEnd(),O=h.split(`
`,1)[0],f=Object.fromEntries(O.split("|").slice(1).map(u=>{const m=u.indexOf("=");return m<0?[u,""]:[u.slice(0,m),u.slice(m+1)]}));return{body:h,fields:f,id:O.split("|",1)[0]}});return{preamble:n.length?e.slice(0,n[0].index).trimEnd():e.trimEnd(),sections:i}}function H(t,e={},n={}){if(n.authorization!=="human")throw new Error("FT_RECONCILIACAO_NAO_AUTORIZADA");const i=$(e.validated||[]),r=$(e.pendingValidation||[]);if(i.length&&n.validatedBy!=="developer")throw new Error("FT_VALIDACAO_DESENVOLVEDOR_AUSENTE");const c=i.find(u=>r.includes(u));if(c)throw new Error(`FT_CLASSIFICACAO_AMBIGUA:${c}`);const o=d.join(t,".ia.rules","state","continue.ia");if(!a.existsSync(o))throw new Error("CONTINUE_CANONICO_AUSENTE");const l=x(a.readFileSync(o,"utf8")),s=new Map;for(const u of l.sections)s.has(u.id)||s.set(u.id,[]),s.get(u.id).push(u);const h=new Map;for(const u of[...i,...r]){const m=s.get(u);if(!m){if(i.includes(u)&&a.existsSync(C(t,u)))continue;throw new Error(`FT_ESTADO_AUSENTE:${u}`)}if(r.includes(u)&&m.length!==1)throw new Error(`FT_ESTADO_DUPLICADO:${u}`);if(m.some(T=>!/^conclu[ií]d[oa]$/iu.test(String(T.fields.status||""))))throw new Error(`FT_NAO_CONCLUIDA:${u}`);h.set(u,Z(t,m))}const O=l.sections.flatMap(u=>i.includes(u.id)?[]:r.includes(u.id)?[W(u,h.get(u.id))]:[u.body]),f=`${[l.preamble,...O].filter(Boolean).join(`

`).trimEnd()}
`;return q(t,i),B(t,f),E(o,f),N(t),{code:"FT_STATE_RECONCILED",pendingValidation:r,stateSha256:p(f),unchanged:[...i].filter(u=>!s.has(u)),validated:i}}function q(t,e){if(!e.length)return 0;const n=d.join(t,".ia.rules","state","decisions","refused","index.json");if(!a.existsSync(n))return 0;const i=JSON.parse(a.readFileSync(n,"utf8"));let r=0;for(const c of i.entries||[])Array.isArray(c.relatedArtifacts)&&(c.relatedArtifacts=c.relatedArtifacts.map(o=>{const l=String(o).match(/^\.ia\.rules\/(?:state\/)?continue\.ia#(FT-\d+)$/u);return!l||!e.includes(l[1])?o:(r+=1,`.ia.rules/state/history/${l[1]}.ia#${l[1]}`)}));return r&&E(n,`${JSON.stringify(i,null,2)}
`),r}function $(t){if(!Array.isArray(t))throw new Error("FT_CLASSIFICACAO_INVALIDA");const e=t.map(n=>String(n||"").trim());for(const n of e)if(!/^FT-\d+$/u.test(n))throw new Error(`FT_ID_INVALIDO:${n}`);if(new Set(e).size!==e.length)throw new Error("FT_ID_DUPLICADO");return e.sort((n,i)=>n.localeCompare(i,"en",{numeric:!0}))}function C(t,e){return d.join(t,w,`${e}.ia`)}function X(t,e){const n=e.body.match(/^historico=([^|\r\n]+)\|sha256=([a-f0-9]{64})$/mu);if(!n)return`${e.body.trimEnd()}
`;const i=A(d.join(w,`${e.id}.ia`));if(A(n[1])!==i)throw new Error(`FT_HISTORICO_PATH_INVALIDO:${e.id}`);const r=C(t,e.id);if(!a.existsSync(r))throw new Error(`FT_HISTORICO_AUSENTE:${e.id}`);const c=a.readFileSync(r,"utf8").replace(/\r\n/gu,`
`);if(p(c)!==n[2])throw new Error(`FT_HISTORICO_HASH_DIVERGENTE:${e.id}`);return c}function Z(t,e){const n=e.map(o=>X(t,o).trimEnd()).join(`

`)+`
`,[i]=e,r=C(t,i.id),c=p(n);if(a.existsSync(r)){if(p(a.readFileSync(r,"utf8"))!==c)throw new Error(`FT_HISTORICO_COLISAO:${i.id}`)}else E(r,n);return{id:i.id,path:A(d.join(w,`${i.id}.ia`)),sha256:c}}function W(t,e){const n=t.body.split(`
`,1)[0],r=[/\|validacao=/u.test(n)?n.replace(/\|validacao=[^|\r\n]+/u,"|validacao=pendente_desenvolvedor"):`${n}|validacao=pendente_desenvolvedor`];for(const c of["objetivo","origem","resultado","verificacoes","pendencias"]){const o=t.body.match(new RegExp(`^${c}=(.*)$`,"mu"));o&&r.push(`${c}=${o[1]}`)}return r.some(c=>c.startsWith("pendencias="))||r.push("pendencias=Validação do desenvolvedor."),r.push(`historico=${e.path}|sha256=${e.sha256}`),r.join(`
`)}function B(t,e){const n=d.join(t,w);a.mkdirSync(n,{recursive:!0});const i=new Set(x(e).sections.map(s=>s.id)),r=a.readdirSync(n,{withFileTypes:!0}).filter(s=>s.isFile()&&/^FT-\d+\.ia$/u.test(s.name)).map(s=>{const h=s.name.slice(0,-3),O=A(d.join(w,s.name)),f=a.readFileSync(d.join(n,s.name),"utf8"),m=(f.split(/\r?\n/u,1)[0].match(/\|nome=([^|\r\n]+)/u)||[])[1]||"Sem nome";return{id:h,name:m,path:O,sha256:p(f),state:i.has(h)?"pendente-validacao":"validada"}}).sort((s,h)=>s.id.localeCompare(h.id,"en",{numeric:!0})),c={schema:"agents-feature-history-index/v1",entries:r};E(d.join(n,"index.json"),`${JSON.stringify(c,null,2)}
`);const o=["# FTs implementadas","","Índice mínimo; carregue somente o histórico da FT pertinente.","",...r.map(s=>`- ${s.id} — ${s.name}; estado: ${s.state}; histórico: \`${A(d.relative(d.join(t,".ia.rules","state"),d.join(t,s.path)))}\`; sha256: \`${s.sha256}\`.`),""].join(`
`);E(d.join(t,z),o);const l=d.join(t,".ia.rules","state","index.json");if(a.existsSync(l)){const s=JSON.parse(a.readFileSync(l,"utf8"));s.history="history/index.json",E(l,`${JSON.stringify(s,null,2)}
`)}return r}function L(){let t="",e="kernel-fallback";try{process.platform==="win32"?(t=V.execFileSync("reg",["query","HKLM\\SOFTWARE\\Microsoft\\Cryptography","/v","MachineGuid"],{encoding:"utf8",windowsHide:!0}).split(/\r?\n/u).find(i=>i.includes("MachineGuid"))?.trim().split(/\s{2,}/u).pop()||"",e="windows-machine-guid-hash"):a.existsSync("/etc/machine-id")&&(t=a.readFileSync("/etc/machine-id","utf8").trim(),e="linux-machine-id-hash")}catch{t=""}const n={platform:I.platform(),release:I.release(),arch:I.arch(),node:process.version};return t||(t=JSON.stringify(n)),{id:p(`agents-env-v1\0${t}`).slice(0,24),source:e,stable:e!=="kernel-fallback",kernel:n}}function Q(t,e){const n=["command","projectHash","timestamp","exitCode"];for(const l of n)if(e[l]===void 0||e[l]==="")throw new Error(`MEMORIA_CAMPO_AUSENTE:${l}`);const i=/(token|password|secret|authorization)\s*[:=]/iu,r=JSON.stringify(e);if(i.test(r))throw new Error("MEMORIA_SEGREDO_RECUSADO");const c=d.join(t,".ia.rules","state","memory.md"),o={...e,environment:L()};return a.appendFileSync(c,`
- \`${o.timestamp}\` ${JSON.stringify(o)}
`,"utf8"),o}function E(t,e){a.mkdirSync(d.dirname(t),{recursive:!0});const n=`${t}.tmp-${process.pid}-${v.randomBytes(4).toString("hex")}`,i=a.openSync(n,"wx");try{a.writeFileSync(i,e,"utf8"),a.fsyncSync(i)}finally{a.closeSync(i)}a.renameSync(n,t)}function p(t){return v.createHash("sha256").update(String(t).replace(/\r\n/gu,`
`),"utf8").digest("hex")}function A(t){return String(t).replace(/\\/gu,"/")}module.exports={CANONICAL_TODO:_,EQUALIZER:b,STATUS_EMOJI:M,assertTodoIaTriaged:k,environmentFingerprint:L,inspectTodoIa:j,locateTodoFiles:D,migrateCanonicalState:P,parseGovernedTodo:y,parseTodoItems:R,concludeFeatureState:J,parseFeatureState:x,reconcileFeatureState:H,recordMemoryResult:Q,syncCanonicalProjections:N,transitionTodoRoot:G};
