declare function require(id: string): any;
declare const process: { exitCode?: number };
const fs=require('node:fs'),ts=require('typescript'),assert=require('node:assert/strict');
const cache: Record<string, any>={};
function load(name: string): any{if(!['verified-process','process-outcome','resilient-operation'].includes(name))throw Error('UNEXPECTED_IMPORT');
if(cache[name])return cache[name];
const api=cache[name]={};
const js=ts.transpileModule(fs.readFileSync('.ia.rules/local/runtime/'+name+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
new Function('require','exports',js)((id: string)=>load(id.replace(/^\.\//,'')),api);
return api;
}const f: typeof import('../.ia.rules/local/runtime/verified-process').executeVerifiedProcess=load('verified-process').executeVerifiedProcess;
(async()=>{let calls: string[]=[];
const r=await f({v:0},async()=>{calls.push('run');
return {status:'completed',exitCode:0,reused:true};
},()=>{calls.push('read');
return {v:1};
},s=>{calls.push('verify');
(s as {v:number}).v=9;
return true;
});
assert.equal(r.status,'completed');
assert.deepEqual(r.state,{v:1});
assert.deepEqual(calls,['run','read','verify']);
for(const evidence of [{status:'running'},{status:'timed_out'},{status:'cancelled'},null]){const r=await f(0,async()=>evidence,()=>{throw Error('MUST_NOT_READ')},()=>{throw Error('MUST_NOT_VERIFY')});
assert.equal(r.status,'blocked');
assert.equal(r.state,0);
}for(const rejected of [false,true]){let reads=0;
const r=await f(0,async()=>{const result={status:'failed',exitCode:1};
if(rejected)throw Object.assign(Error('PRIVATE_ERROR'),{result});
return result;
},()=>{reads++;
return 1},()=>true);
assert.equal(r.status,'exhausted');
assert.equal(reads,0);
assert.equal(JSON.stringify(r).includes('PRIVATE_ERROR'),false);
}assert.equal((await f(0,async()=>{throw Error('PRIVATE_ERROR')},()=>1,()=>true)).status,'blocked');
assert.equal((await f(0,async()=>({status:'completed',exitCode:0}),()=>1,()=>false)).status,'exhausted');
let runs=0;
await assert.rejects(()=>f(undefined,async()=>{runs++;
return {}},()=>1,()=>true));
assert.equal(runs,0);
let release!: (value: unknown) => void;
const pending=new Promise<unknown>(r=>release=r);
let reads=0;
const promise=f(0,()=>pending,()=>{reads++;
return 1},()=>true);
await Promise.resolve();
assert.equal(reads,0);
release({status:'completed',exitCode:0});
assert.equal((await promise).status,'completed');
console.log('VERIFIED_PROCESS_TEST_OK');
})().catch(e=>{console.error(e);
process.exitCode=1});

export {};
